version: "3.9"

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  redis-server:
    container_name: redis-server
    image: redis:7.4.2-alpine
    ports:
      - "6379:6379"
